version: '3'
services:
  inx-score-ml:
    container_name: inx-score-ml
    build:
      context: .
      dockerfile: Dockerfile
    environment: # specify the env-variables here
      # variables from .env file or system
      # sometimes the console won't show print messages,
      # using PYTHONUNBUFFERED: 1 can fix this
      PYTHONUNBUFFERED: 1
